version: "3.8"
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pin_app_client_api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./src:/app/src
    restart: always
  postgres:
    image: postgres:13
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME}