version: "3.8"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_DB_PASS}@postgres:5432/db
      NODE_ENV: ${NODE_ENV}
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: npm run dev
    volumes:
      - ./pinApp:/app
      - /app/node_modules
  postgres:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - pinAppChallenge
networks:
  pinAppChallenge: